version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - IS_DOCKER=true
      - PORT=4000
      - XERO_API_URL=http://host.docker.internal:3000/api.xro/2.0/Reports/BalanceSheet
    # depends_on:
    #   - xero-api
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    ports:
      - "3006:3006"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:4000
    volumes:
      - ./client:/app
      - /app/node_modules

  # xero-api:
  #   image: jaypeng2015/show-me-the-money
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
