services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - IS_DOCKER=true
      - PORT=4000
      - XERO_API_URL=http://xero-api:3000/api.xro/2.0/Reports/BalanceSheet
    # depends_on:
    #   - xero-api
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3006:3006"
    environment:
      - REACT_APP_SERVER_URL=http://server:4000
    depends_on: 
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

  xero-api:
    image: jaypeng2015/show-me-the-money
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
